name: Build & Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - name: build_win
            cmd: build:win
          - name: build_port_win
            cmd: build:port:win

    name: Build on windows (${{ matrix.cmd  }})
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: pnpm run ${{ matrix.cmd  }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.cmd  }}
          path: |
            dist/
          if-no-files-found: ignore

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare files for release
        run: |
          mkdir -p installer
          cp -R artifacts/build_win/* installer/ || true
          cd installer
          zip -r ../yasig-menu-installer-${{ github.ref_name }}.zip .
          cd ..

          mkdir -p portable
          cp artifacts/build_port_win/*.exe portable/yasig-menu-portable-${{ github.ref_name }}.exe || true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            yasig-menu-installer*.zip
            portable/yasig-menu-portable*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
